server:
  port: 3333

spring:
  application:
    name: GATEWAY-API
    
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: welcome-service
          uri: lb://WELCOME-API
          predicates:
            - Path=/api1/**
          filters:
            - StripPrefix=1
        - id: greet-service
          uri: lb://GREET-API
          predicates:
            - Path=/api2/**
          filters:
            - StripPrefix=1


